export const queryKeys = {
  subjects: ['subjects'] as const,
  lessons: (subjectId: string) => ['lessons', subjectId] as const,
  lesson: (lessonId: string) => ['lesson', lessonId] as const,
  progress: (userId: string) => ['lesson-progress', userId] as const,
  streak: (userId: string) => ['streak', userId] as const,
  subscription: (userId: string) => ['subscription', userId] as const,
  exercises: (lessonId: string) => ['exercises', lessonId] as const,
  exerciseProgress: (userId: string) => ['exercise-progress', userId] as const,
  flashcardDecks: ['flashcard-decks'] as const,
  flashcards: (deckId: string) => ['flashcards', deckId] as const,
  srsReviews: (userId: string) => ['srs-reviews', userId] as const,
  aiConversations: (userId: string) => ['ai-conversations', userId] as const,
  aiMessages: (conversationId: string) => ['ai-messages', conversationId] as const,
  leagueBoard: (userId: string) => ['league-board', userId] as const,
  pendingCelebrations: (userId: string) => ['pending-celebrations', userId] as const,
};
