-- Data-driven course catalog, replacing one hardcoded .tsx file per course.
-- `content` is nullable: it is filled in on the student's first visit to a
-- course (by the generate-course edge function) rather than pre-generated
-- for the whole curriculum up front, then cached here for every student
-- after that. The 11 Histoire-Géographie 3ème courses that already existed
-- as hand-authored static screens are migrated below with their content
-- already populated, proving the pipeline end-to-end before it's used to
-- grow into new grades/subjects.
create table public.courses (
  id text primary key,
  grade text not null,
  subject text not null,
  title text not null,
  order_index integer not null,
  requires_course_id text references public.courses (id),
  content jsonb,
  content_generated_at timestamptz,
  created_at timestamptz not null default now()
);

create index courses_grade_subject_idx on public.courses (grade, subject, order_index);

alter table public.courses enable row level security;

-- Course content is shared curriculum, not user data: any signed-in student
-- can read the whole catalog. Only the generate-course edge function
-- (service role, bypasses RLS) writes to it — no insert/update policy for
-- regular users.
create policy "Authenticated users can read courses"
  on public.courses for select
  to authenticated
  using (true);

insert into public.courses (id, grade, subject, title, order_index, requires_course_id, content, content_generated_at) values

('mondialisation', '3eme', 'geographie', $$L'Afrique face à la mondialisation$$, 1, null, jsonb_build_object('paragraphs', array[
$$Tu sais qu'il y a quelques années, les 8 pays les plus industrialisés du monde se sont réunis pour parler du commerce international — et aucun pays africain n'était présent. Pas un seul. Pourquoi, à ton avis, alors que l'Afrique compte 1,3 milliard d'habitants et regorge de ressources ?$$,
$$En fait, l'Afrique participe très peu aux échanges commerciaux mondiaux : elle représente moins de 4 % du commerce mondial. Pour comparer, l'Union européenne à elle seule en représente 43 % — presque la moitié. La Chine et le Japon ensemble, 33 %. Les États-Unis, 13 %. Le reste du monde, dont l'Afrique, se partage ce qui reste.$$,
$$Et ce que l'Afrique échange n'est pas équilibré : elle exporte surtout des matières premières — café, cacao, or, diamant, fer, bois — souvent brutes, pas transformées. Et elle importe des produits déjà fabriqués : voitures, médicaments, équipements. Résultat, elle profite beaucoup moins de la valeur ajoutée de ce qu'elle produit elle-même.$$,
$$Pourquoi cette situation ? Plusieurs raisons s'additionnent : peu d'usines pour transformer les matières premières sur place, des infrastructures insuffisantes (routes, ports), une dette très lourde qui limite les investissements, et parfois des conflits qui freinent le développement.$$,
$$Mais ce n'est pas figé : plus de formation pour la jeunesse, plus d'industries locales, des regroupements économiques régionaux comme la CEDEAO, et un meilleur accès aux nouvelles technologies sont des pistes concrètes pour que l'Afrique prenne une place plus importante dans les décennies à venir.$$,
$$Et si on te le demande précisément à l'examen : c'est le fait que les économies des différents pays s'intègrent et deviennent interdépendantes, au point de former un seul grand marché à l'échelle du monde — avec une circulation de plus en plus intense des capitaux, des informations, des marchandises et des personnes entre les pays.$$
]::text[]), now()),

('acteurs', '3eme', 'geographie', $$Les acteurs de la mondialisation$$, 2, 'mondialisation', jsonb_build_object('paragraphs', array[
$$Tu as sûrement déjà bu un Coca-Cola, ou vu une pub Nestlé — deux marques présentes dans la quasi-totalité des pays du monde. Comment des entreprises deviennent-elles aussi présentes partout à la fois ? La mondialisation ne se fait pas toute seule : trois types d'acteurs la font vraiment fonctionner.$$,
$$D'abord, les États eux-mêmes. Ils construisent les routes, les ports, les aéroports qui permettent aux marchandises de circuler. Certains créent aussi des zones franches — des zones avec des avantages fiscaux, pour attirer les entreprises étrangères chez eux.$$,
$$Ensuite, les firmes transnationales, comme Coca-Cola ou Nestlé. Ce sont des entreprises présentes dans plusieurs pays à la fois, qui produisent parfois une partie de leurs produits dans un pays et une autre ailleurs, avant d'assembler et de vendre partout. Il en existe plus de 80 000 dans le monde, et elles réalisent à elles seules une grande partie du commerce mondial.$$,
$$Enfin, les institutions internationales, comme le FMI (qui prête de l'argent aux pays en difficulté) ou l'OMC (qui encourage les échanges entre pays et essaie de limiter ce qui les freine). Ces trois acteurs agissent ensemble : un État construit un port, une firme s'y installe pour exporter, une institution internationale finance parfois les infrastructures qui rendent tout ça possible.$$,
$$Et si on te le demande précisément à l'examen : une firme transnationale (ou multinationale) est une entreprise qui exerce son activité dans au moins 5 pays différents, directement ou par l'intermédiaire de filiales, avec un chiffre d'affaires généralement supérieur à 500 millions de dollars.$$
]::text[]), now()),

('atouts', '3eme', 'geographie', $$Les atouts naturels et humains du développement économique de la Côte d'Ivoire$$, 3, 'acteurs', jsonb_build_object('paragraphs', array[
$$Le chocolat que mange une bonne partie du monde vient, pour près de la moitié, d'un seul pays : la Côte d'Ivoire. Comment un pays devient-il le premier producteur mondial d'un produit ? La réponse tient en deux mots : des atouts, naturels et humains, que le pays a su exploiter.$$,
$$D'abord, les atouts naturels — ce que le milieu physique offre directement. La Côte d'Ivoire a un climat chaud et humide, idéal pour le cacao, le café, l'hévéa (le caoutchouc) et le palmier à huile. Ses sols sont fertiles, surtout dans le sud forestier. Elle a aussi une façade maritime avec deux grands ports (Abidjan et San Pedro), ce qui facilite l'exportation vers le reste du monde. Le sous-sol contient du pétrole et du gaz au large des côtes, et les fleuves permettent de produire de l'électricité.$$,
$$Ensuite, les atouts humains — ce que la population apporte. La Côte d'Ivoire a une population jeune et nombreuse, donc une main-d'œuvre importante pour l'agriculture et l'industrie. Une longue tradition paysanne de culture du cacao et du café s'est transmise de génération en génération. Abidjan, la capitale économique, concentre les activités, les entreprises et la main-d'œuvre qualifiée.$$,
$$Ces deux types d'atouts se complètent : un sol fertile ne sert à rien sans des paysans pour le cultiver, et une population nombreuse a besoin de ressources naturelles à exploiter pour créer de la richesse.$$,
$$Et si on te le demande précisément à l'examen : un atout naturel est une ressource offerte par le milieu physique (climat, sol, eau, sous-sol) qu'un pays peut exploiter pour se développer. Un atout humain est une ressource liée à la population (nombre, main-d'œuvre, savoir-faire) qu'un pays peut mobiliser pour se développer.$$
]::text[]), now()),

('secteurs', '3eme', 'geographie', $$Les secteurs d'activités économiques de la Côte d'Ivoire$$, 4, 'atouts', jsonb_build_object('paragraphs', array[
$$Le cacao qu'on a vu dans le cours précédent ne pousse pas tout seul jusqu'aux étagères des magasins en Europe. Entre le champ et la tablette de chocolat, il y a toute une chaîne de métiers différents. Ces métiers, on les regroupe en trois grandes familles : les secteurs d'activité économique.$$,
$$D'abord, le secteur primaire : l'exploitation directe des ressources naturelles. En Côte d'Ivoire, c'est l'agriculture (cacao, café, hévéa, anacarde, palmier à huile), la pêche, et l'extraction (pétrole, or). C'est historiquement le secteur qui emploie le plus d'Ivoiriens, surtout dans les zones rurales.$$,
$$Ensuite, le secteur secondaire : la transformation de ces matières premières. Les usines qui transforment le cacao en pâte ou en beurre de cacao en font partie — la Côte d'Ivoire est d'ailleurs devenue le premier pays transformateur de cacao au monde, devant les Pays-Bas. On y trouve aussi le textile et le bâtiment et travaux publics (BTP).$$,
$$Enfin, le secteur tertiaire : les services. Le commerce, les transports, les banques, le tourisme, l'administration. Ce secteur est très concentré à Abidjan, la capitale économique du pays.$$,
$$Et si on te le demande précisément à l'examen : le secteur primaire regroupe les activités d'exploitation directe des ressources naturelles (agriculture, pêche, extraction). Le secteur secondaire regroupe les activités de transformation de ces ressources (industrie). Le secteur tertiaire regroupe les activités de service (commerce, transport, administration, tourisme).$$
]::text[]), now()),

('colonisation', '3eme', 'histoire', $$Le mouvement impérialiste et la colonisation en Côte d'Ivoire$$, 1, null, jsonb_build_object('paragraphs', array[
$$Avant 1893, la Côte d'Ivoire n'existait pas en tant que pays avec ces frontières-là. Comment un territoire aussi vaste, peuplé de dizaines de groupes différents, s'est-il retrouvé sous la domination d'un seul pays européen, la France, en l'espace de quelques décennies ?$$,
$$À la fin du XIXe siècle, les grandes puissances européennes (France, Grande-Bretagne, Allemagne, Belgique...) se lancent dans une course pour contrôler des territoires en Afrique : c'est l'impérialisme colonial. Pour éviter les conflits entre elles, elles se réunissent à la conférence de Berlin, entre 1884 et 1885, où elles se partagent le continent africain sur une carte, sans tenir compte des peuples qui y vivent déjà. La France obtient une large zone en Afrique de l'Ouest, qui inclut le territoire de l'actuelle Côte d'Ivoire.$$,
$$Sur le terrain, la France doit encore conquérir militairement ce territoire, ce qui prend plusieurs années. Des résistances locales s'organisent : la plus connue est celle de Samory Touré, qui combat les troupes françaises dans l'ouest du pays avant d'être capturé en 1898. En 1893, la Côte d'Ivoire est officiellement déclarée colonie française, avec Louis-Gustave Binger comme premier gouverneur. En 1895, elle est intégrée à un plus grand ensemble administratif, l'Afrique Occidentale Française (AOF), qui regroupe plusieurs colonies françaises de la région.$$,
$$Une fois la colonisation en place, l'administration française impose de nouvelles règles : le travail forcé (les populations sont obligées de travailler gratuitement sur des chantiers ou des plantations), l'impôt de capitation (une taxe payée par chaque habitant), et le code de l'indigénat (un ensemble de lois qui prive les populations locales de la plupart de leurs droits). Le pays est aussi réorganisé économiquement autour de l'exportation de matières premières comme le café et le cacao, avec la construction de routes, de ports et d'une voie ferrée pour faciliter ce commerce vers la France.$$,
$$Et si on te le demande précisément à l'examen : l'impérialisme est la politique par laquelle une puissance étend sa domination politique, économique et territoriale sur d'autres régions du monde ; la colonisation est la mise en œuvre concrète de cette domination sur un territoire donné. La Côte d'Ivoire devient officiellement colonie française en 1893.$$
]::text[]), now()),

('independance', '3eme', 'histoire', $$L'accession de la Côte d'Ivoire à l'indépendance$$, 2, 'colonisation', jsonb_build_object('paragraphs', array[
$$Le 7 août 1960, le drapeau français est descendu à Abidjan pour la dernière fois. Comment un territoire colonisé pendant près de 70 ans a-t-il obtenu son indépendance en quelques années seulement, et pourquoi cette indépendance s'est-elle faite sans guerre, contrairement à d'autres colonies africaines ?$$,
$$Après la Seconde Guerre mondiale, les populations colonisées réclament de plus en plus de droits. En Côte d'Ivoire, Félix Houphouët-Boigny, planteur et médecin, devient une figure politique majeure. En 1946, il fonde le Parti Démocratique de Côte d'Ivoire (PDCI) et participe à la création du Rassemblement Démocratique Africain (RDA), un mouvement qui regroupe plusieurs partis de l'Afrique française, lors du congrès de Bamako. La même année, en tant que député français, il fait voter la loi qui abolit le travail forcé dans les colonies.$$,
$$La marche vers l'indépendance se fait ensuite par étapes. En 1956, la loi-cadre Defferre donne davantage d'autonomie interne aux territoires d'Afrique noire française : chaque territoire obtient son propre gouvernement local, même si la France garde le contrôle des grandes décisions. Cette évolution progressive, obtenue par la négociation politique plutôt que par la lutte armée, explique pourquoi l'indépendance ivoirienne se fait de manière pacifique.$$,
$$Le 7 août 1960, la Côte d'Ivoire devient officiellement indépendante, et Félix Houphouët-Boigny en devient le premier président. Cette année 1960 est marquante à l'échelle du continent : on l'appelle parfois « l'année de l'Afrique », car dix-sept pays africains deviennent indépendants la même année.$$,
$$Et si on te le demande précisément à l'examen : la Côte d'Ivoire accède à l'indépendance le 7 août 1960, après une évolution politique progressive marquée par l'abolition du travail forcé (1946) et la loi-cadre Defferre (1956) ; Félix Houphouët-Boigny en devient le premier président.$$
]::text[]), now()),

('crises-afrique', '3eme', 'histoire', $$Causes et caractères des crises sociopolitiques de l'Afrique indépendante$$, 3, 'independance', jsonb_build_object('paragraphs', array[
$$Beaucoup de pays africains, une fois indépendants, espéraient une période de stabilité et de développement. Pourtant, dans les décennies qui ont suivi, plusieurs d'entre eux ont connu coups d'État, guerres civiles ou dictatures. Pourquoi l'indépendance n'a-t-elle pas suffi à garantir la stabilité politique ?$$,
$$Plusieurs causes expliquent ces crises. D'abord, les frontières héritées de la colonisation ont souvent été tracées sans tenir compte des peuples et des royaumes précoloniaux, regroupant de force des populations différentes dans un même État ou, au contraire, séparant un même peuple entre plusieurs pays — ce qui crée des tensions. Ensuite, beaucoup de nouveaux États ont adopté le système du parti unique, où un seul parti politique est autorisé, ce qui limite les libertés et pousse parfois l'opposition à se tourner vers la violence. Enfin, la pauvreté, les inégalités économiques et les rivalités pour le contrôle des ressources naturelles alimentent aussi les tensions internes.$$,
$$Le contexte international joue également un rôle : pendant la guerre froide (1947-1991), les États-Unis et l'URSS soutiennent parfois, financièrement ou militairement, des régimes ou des rébellions en Afrique pour étendre leur influence, ce qui aggrave certains conflits internes.$$,
$$Ces crises prennent des formes variées : des coups d'État militaires, où l'armée renverse le pouvoir civil par la force ; des guerres civiles, qui opposent des groupes armés à l'intérieur d'un même pays ; ou encore des régimes autoritaires, qui restreignent les libertés pour se maintenir au pouvoir.$$,
$$Et si on te le demande précisément à l'examen : les crises sociopolitiques de l'Afrique indépendante s'expliquent par des causes multiples (frontières héritées de la colonisation, système du parti unique, pauvreté, ingérences extérieures liées à la guerre froide) et se manifestent sous des formes variées (coups d'État, guerres civiles, régimes autoritaires).$$
]::text[]), now()),

('rwanda', '3eme', 'histoire', $$La crise rwandaise : de la guerre au génocide des Tutsi (1990-1994)$$, 4, 'crises-afrique', jsonb_build_object('paragraphs', array[
$$Entre avril et juillet 1994, environ 800 000 personnes sont tuées au Rwanda en l'espace de cent jours à peine — l'un des génocides les plus rapides de l'histoire. Comment un pays a-t-il basculé aussi vite dans une telle violence ?$$,
$$Le Rwanda compte deux groupes principaux, les Hutu (majoritaires) et les Tutsi (minoritaires), ainsi qu'une petite minorité twa. Pendant la colonisation belge, l'administration renforce la distinction entre ces groupes, notamment en introduisant des cartes d'identité mentionnant l'appartenance ethnique. Ce climat de tension s'aggrave après l'indépendance du Rwanda (1962), avec plusieurs épisodes de violence contre les Tutsi, poussant beaucoup d'entre eux à fuir vers les pays voisins.$$,
$$En octobre 1990, des réfugiés tutsi exilés, regroupés au sein du Front Patriotique Rwandais (FPR), envahissent le Rwanda depuis l'Ouganda, déclenchant une guerre civile. Après plusieurs années de combats, un accord de paix, les accords d'Arusha, est signé en août 1993 entre le gouvernement rwandais et le FPR, prévoyant un partage du pouvoir. Mais les tensions restent très fortes, et une partie du pouvoir hutu prépare en secret l'élimination des Tutsi.$$,
$$Le 6 avril 1994, l'avion transportant le président rwandais Juvénal Habyarimana est abattu près de Kigali. Cet événement sert de déclencheur : dès les heures suivantes, des massacres systématiques de Tutsi (et de Hutu modérés) commencent, organisés par une partie de l'armée et des milices. En l'espace d'environ cent jours, entre avril et juillet 1994, environ 800 000 personnes sont tuées. Le génocide prend fin lorsque le FPR reprend le contrôle du pays en juillet 1994.$$,
$$Et si on te le demande précisément à l'examen : le génocide des Tutsi au Rwanda se déroule entre avril et juillet 1994, déclenché par l'attentat du 6 avril 1994 contre l'avion du président Habyarimana, dans le contexte d'une guerre civile commencée en 1990 entre le gouvernement et le Front Patriotique Rwandais (FPR).$$
]::text[]), now()),

('guerre-mondiale', '3eme', 'histoire', $$Les causes, les caractères et les conséquences de la Seconde Guerre mondiale$$, 5, 'rwanda', jsonb_build_object('paragraphs', array[
$$En seulement six ans, entre 1939 et 1945, la Seconde Guerre mondiale va faire plus de morts que n'importe quel autre conflit de l'histoire. Comment l'Europe a-t-elle pu retomber dans une guerre mondiale à peine vingt ans après la fin de la précédente ?$$,
$$Plusieurs causes expliquent le déclenchement du conflit. Le traité de Versailles de 1919, qui impose de lourdes sanctions à l'Allemagne après la Première Guerre mondiale, nourrit un profond ressentiment dans la population allemande. La crise économique mondiale de 1929 aggrave la situation et favorise la montée de régimes autoritaires, notamment le nazisme d'Adolf Hitler, qui devient chancelier d'Allemagne en 1933. Hitler mène ensuite une politique d'expansion territoriale (annexion de l'Autriche en 1938, puis d'une partie de la Tchécoslovaquie), jusqu'à l'invasion de la Pologne le 1er septembre 1939, qui pousse la France et le Royaume-Uni à déclarer la guerre à l'Allemagne.$$,
$$Cette guerre oppose deux camps : les puissances de l'Axe (Allemagne, Italie, Japon) contre les Alliés (France, Royaume-Uni, puis l'URSS à partir de 1941 et les États-Unis à partir de décembre 1941, après l'attaque japonaise de Pearl Harbor). C'est une guerre totale, qui mobilise non seulement les armées mais aussi les économies et les populations civiles des pays impliqués, y compris les colonies : des dizaines de milliers de soldats africains, comme les tirailleurs sénégalais, combattent aux côtés de la France. Le conflit est aussi marqué par un génocide, la Shoah, l'extermination organisée des Juifs d'Europe par le régime nazi.$$,
$$L'Allemagne capitule le 8 mai 1945. Le Japon capitule à son tour en septembre 1945, après que les États-Unis ont largué deux bombes atomiques sur Hiroshima et Nagasaki en août 1945. Le bilan humain est immense : plus de 50 millions de morts dans le monde, même si les estimations varient selon les sources. La guerre entraîne aussi la création de l'Organisation des Nations Unies (ONU) en 1945, pour tenter d'éviter un nouveau conflit mondial, et marque le début de nouvelles tensions entre les États-Unis et l'URSS, qui donneront naissance à la guerre froide.$$,
$$Et si on te le demande précisément à l'examen : la Seconde Guerre mondiale (1939-1945) oppose les puissances de l'Axe (Allemagne, Italie, Japon) aux Alliés (France, Royaume-Uni, URSS, États-Unis) ; elle se termine par la capitulation de l'Allemagne (8 mai 1945) puis du Japon (septembre 1945).$$
]::text[]), now()),

('onu', '3eme', 'histoire', $$L'Organisation des Nations Unies (ONU)$$, 6, 'guerre-mondiale', jsonb_build_object('paragraphs', array[
$$Après les ravages de la Seconde Guerre mondiale, les pays vainqueurs veulent éviter qu'un tel conflit ne se reproduise. Leur réponse : créer une organisation mondiale chargée de maintenir la paix. Mais comment une telle organisation peut-elle réellement empêcher la guerre entre États souverains ?$$,
$$L'ONU est créée en 1945, à la fin de la Seconde Guerre mondiale, pour remplacer la Société des Nations (SDN), une précédente organisation internationale créée après la Première Guerre mondiale mais qui avait échoué à empêcher un nouveau conflit mondial. La charte des Nations Unies est signée à San Francisco en juin 1945, et l'organisation entre officiellement en fonction le 24 octobre 1945.$$,
$$L'ONU est organisée autour de plusieurs organes principaux. L'Assemblée générale réunit tous les pays membres, chacun disposant d'une voix. Le Conseil de sécurité, plus restreint, est chargé des questions de paix et de sécurité internationale ; il comprend cinq membres permanents disposant d'un droit de veto (les États-Unis, la Russie, la Chine, la France et le Royaume-Uni), et des membres non permanents élus pour deux ans. Le Secrétariat, dirigé par le secrétaire général, assure le fonctionnement quotidien de l'organisation, dont le siège se trouve à New York.$$,
$$L'ONU a pour missions principales de maintenir la paix entre les États, de promouvoir les droits humains — elle adopte notamment la Déclaration universelle des droits de l'homme en 1948 — et d'encourager le développement économique et social dans le monde. La Côte d'Ivoire, comme la plupart des pays africains devenus indépendants, rejoint l'ONU en 1960, l'année de son indépendance.$$,
$$Et si on te le demande précisément à l'examen : l'ONU est créée en 1945 pour maintenir la paix et la sécurité internationale ; son Conseil de sécurité comprend cinq membres permanents avec droit de veto (États-Unis, Russie, Chine, France, Royaume-Uni), et son siège se trouve à New York.$$
]::text[]), now()),

('ua', '3eme', 'histoire', $$L'Union Africaine (UA)$$, 7, 'onu', jsonb_build_object('paragraphs', array[
$$En 2002, l'Organisation de l'Unité Africaine (OUA), créée près de 40 ans plus tôt, laisse place à une nouvelle organisation continentale : l'Union Africaine. Pourquoi les pays africains ont-ils choisi de transformer leur organisation commune plutôt que de simplement la conserver ?$$,
$$Au moment des indépendances africaines, les chefs d'État du continent créent, le 25 mai 1963 à Addis-Abeba (Éthiopie), l'Organisation de l'Unité Africaine (OUA). Son objectif est de renforcer la solidarité entre les États africains, de défendre leur souveraineté et leur intégrité territoriale, et de soutenir les mouvements de libération encore en lutte contre la colonisation ou l'apartheid. Mais l'OUA est critiquée pour son manque de moyens d'action face aux crises internes des pays membres, au nom du principe de non-ingérence.$$,
$$À partir de la fin des années 1990, plusieurs dirigeants africains, notamment le libyen Mouammar Kadhafi, proposent de transformer l'OUA en une organisation plus intégrée, capable d'agir plus efficacement, notamment sur les plans économique et politique. Cette idée est formalisée par la déclaration de Syrte en 1999, puis l'Union Africaine est officiellement lancée en 2002, lors d'un sommet à Durban, en Afrique du Sud.$$,
$$L'Union Africaine reprend son siège à Addis-Abeba. Elle se dote de nouveaux outils par rapport à l'OUA : un Parlement panafricain, une Cour africaine des droits de l'homme et des peuples, et surtout la possibilité d'intervenir dans un pays membre en cas de crimes graves (génocide, crimes de guerre), ce que l'OUA refusait auparavant. Chaque année, le 25 mai est célébré comme la « Journée de l'Afrique », en souvenir de la création de l'OUA.$$,
$$Et si on te le demande précisément à l'examen : l'Organisation de l'Unité Africaine (OUA), créée en 1963 à Addis-Abeba, devient l'Union Africaine (UA) en 2002 ; l'UA vise une intégration plus poussée entre États africains et se donne, contrairement à l'OUA, le droit d'intervenir dans un pays membre en cas de crimes graves.$$
]::text[]), now());
